// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiuk2pf5i_7maB128Ug_0OJ1mV6SYNNGU',
    appId: '1:23501538710:web:c8ad593b105c2d0f4fc9b7',
    messagingSenderId: '23501538710',
    projectId: 'chikandandi-blood-donors-48',
    authDomain: 'chikandandi-blood-donors-48.firebaseapp.com',
    storageBucket: 'chikandandi-blood-donors-48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7_9Vd-66QKky4BeIegFOm8OCguLuZC8',
    appId: '1:23501538710:android:5b2c25e4dfd8db944fc9b7',
    messagingSenderId: '23501538710',
    projectId: 'chikandandi-blood-donors-48',
    storageBucket: 'chikandandi-blood-donors-48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkPlI8-7gwF_tdFthJh7BsYlUPv1pgBXk',
    appId: '1:23501538710:ios:6b74efdb329028524fc9b7',
    messagingSenderId: '23501538710',
    projectId: 'chikandandi-blood-donors-48',
    storageBucket: 'chikandandi-blood-donors-48.firebasestorage.app',
    iosBundleId: 'com.example.chikandandiBloodDonors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkPlI8-7gwF_tdFthJh7BsYlUPv1pgBXk',
    appId: '1:23501538710:ios:6b74efdb329028524fc9b7',
    messagingSenderId: '23501538710',
    projectId: 'chikandandi-blood-donors-48',
    storageBucket: 'chikandandi-blood-donors-48.firebasestorage.app',
    iosBundleId: 'com.example.chikandandiBloodDonors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiuk2pf5i_7maB128Ug_0OJ1mV6SYNNGU',
    appId: '1:23501538710:web:80c7ba1377cd655a4fc9b7',
    messagingSenderId: '23501538710',
    projectId: 'chikandandi-blood-donors-48',
    authDomain: 'chikandandi-blood-donors-48.firebaseapp.com',
    storageBucket: 'chikandandi-blood-donors-48.firebasestorage.app',
  );
}
